### ISSUE TITLE
Found pyserini 0.20 gives different result with version 0.12

### ISSUE THREAD

**Issue by kwang2049** [castorini/pyserini#1448]
I did an experiment on BeIR/hotpotqa with pyserini BM25 and I found the two versions of pyserini 0.20.0 vs 0.12.0 give different results (nDCG@10 0.56742 vs 0.60275)
https://colab.research.google.com/drive/1Qmw_5hn9NlI681Th_E1wcN8zG-moUwLP?usp=sharing

I found the issue is due to the indexing part (using 0.20.0 on 0.12.0 index gives the same result), but I do not know more details. They actually yield indices of different sizes (1.3GB vs 1.5GB)

**Comment by MXueguang** [comment]
I think it is because of this change
https://github.com/castorini/anserini/commit/25c6d398f7dbe710663d87eb5dbbaf1deb861606

With the newer version, we need to specify the fields to index at indexing time if using DefaultLuceneDocuentGenerator.

the issue here is title field does not get indexed properly with 0.20.0, thats way (1.3GB v.s. 1.5GB)

**Comment by kwang2049** [comment]
Thanks! Yeah, now it makes sense. I tried adding `-fields title` and the results are matched now
