### ISSUE TITLE
AutoQueryEncoder not using query prefixes (for E5-like and other models)

### ISSUE THREAD

**Issue by orionw** [castorini/pyserini#1812]
Hi there!

Sorry, would make this a PR but I didn't have enough time to get around to it. Thanks again for adding prefixes so we could use models like E5. (issue https://github.com/castorini/pyserini/issues/1720)

When using an E5-like model though, the code uses AutoQueryEncoder which ignores the prefix for the query. It's a pretty simple fix (a few lines). See https://github.com/castorini/pyserini/blob/master/pyserini/search/faiss/_searcher.py#L371

It should be like it is for some of the other classes (like how DkrrDprQueryEncoder handles it) if I understand correctly: https://github.com/castorini/pyserini/blob/2bb342acc124c69ec4fe13ebc3be0bd5a5bf497c/pyserini/search/faiss/_searcher.py#L244

and 

https://github.com/castorini/pyserini/blob/2bb342acc124c69ec4fe13ebc3be0bd5a5bf497c/pyserini/search/faiss/_searcher.py#L233

If I am misunderstanding which class E5 models go to, lmk, but I think they are supposed to go to AutoQueryEncoder.

**Comment by MXueguang** [comment]
Hi @orionw , in pyserini.search.faiss, we are currently using AutoQueryEncoder from pyserini.encode, rather than pyserini.search.faiss._searcher. The AutoQueryEncoder in _searcher is deprecated and would be removed.

https://github.com/castorini/pyserini/blob/2bb342acc124c69ec4fe13ebc3be0bd5a5bf497c/pyserini/search/faiss/__main__.py#L27C61-L27C77

**Comment by lintool** [comment]
Closed by #2008
