### ISSUE TITLE
Guido's materials for AFIRM 2019

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#3]
Hi @zeynepakkalyoncu we should check out Guido's materials for AFIRM 2019:
https://github.com/ielab/afirm2019

**Comment by zeynepakkalyoncu** [comment]
Thanks, this is very helpful! Charlie and I came up with a similar outline on Wednesday:

- Brief intro to Colab + Python (through text processing stuff on a sample MS MARCO passage)
- Explore the test collection, MS MARCO (this is where we want to use some of the functionalities from I-REX as you suggested)
- Indexing
- Interactive querying (similar to what we have in the README, again we can visualize the document vectors, similarities, etc.)
- Running batch experiment / evaluating TREC runs
- Re-ranking (with BERT might work, since we already have the Colab for the demo)

Do you have any other suggestions?

**Comment by lintool** [comment]
Feedback inline:

> + Brief intro to Colab + Python (through text processing stuff on a sample MS MARCO passage)

I assume this is things like tokenization, stemming, etc. with NLTK, Spacy, or whatever?
Do you want to do this from the raw JSON collection or fetching doc from the index?

> Indexing

hrm... doing this from Python is going to be a challenge, I think...

> Interactive querying (similar to what we have in the README, again we can visualize the document vectors, similarities, etc.)
> Running batch experiment / evaluating TREC runs
> Re-ranking (with BERT might work, since we already have the Colab for the demo)

sg

**Comment by lintool** [comment]
Adding to the wish-list of functionalities: pull a raw document from the collection, demonstrate analysis (tokenization/stemming) with different analyzers (e.g., porter vs. krovetz).

**Comment by sipah00** [comment]
@lintool I have collection of some passages, how can I index it so that I can use functions in `pysearch`.
could you please share me link to documentation which describe this step in `pyserini`

**Comment by lintool** [comment]
@sipah00 easiest is probably this: https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md

Put it in the same format as the MS MARCO data, and then you can just reuse the instructions there and the "Pyserini demo on MS MARCO passage retrieval task" notebook here: https://github.com/castorini/anserini-notebooks

**Comment by sipah00** [comment]
Thank you
