### ISSUE TITLE
Intra-query parallelism with pyserini

### ISSUE THREAD

**Issue by cadurosar** [castorini/pyserini#312]
Hi,

Thanks for this great package. I was wondering if it is possible to use Lucene intra-query parallelism (http://blog.mikemccandless.com/2019/10/concurrent-query-execution-in-apache.html https://issues.apache.org/jira/browse/LUCENE-2837) through pyserini in order to reduce the latency of searches. 

I'm not sure if I'm correct on this, but I believe that having intra-query parallelism would allow one to obtain a fairer latency comparison between sparse indexes using pyserini (CPU, possibly multithreaded) and dense indexes using faiss (CPU/GPU, normally multithreaded). What do you think?

Thanks in advance.

**Comment by lintool** [comment]
Hi @cadurosar - thanks for your interest in our work... sorry about the delay, just getting to this now.

While interesting, I don't think this is a critically-needed feature at this point. Intra-query parallelism, as the blog post notes, can be tricky to tune, since there's overhead in merging results.

We can certainly revisit later, but I think we have higher priorities at the moment...
