### ISSUE TITLE
Issue with Faiss

### ISSUE THREAD

**Issue by NeverInAsh** [castorini/pyserini#403]
HI Pyserini Team,
Thanks for this excellent package. While installing pyserini from here i realise it is downloading faiss-cpu as a dependency from pip channel , I think this should be changed as this pre-compiled whl file causes swig dll load error on windows system.

But if i install faiss-cpu from the channel mentioned on the official repo, everything works fine.
conda create -n my_new_environment -c pytorch faiss-cpu python=3.8

Is there a version of pyserini which doesn't require faiss as dependency ?

**Comment by h-vetinari** [comment]
@NeverInAsh 
`pip install` and `conda install` shouldn't be mixed whenever possible - the tools don't really "talk" to each other and might step on each others toes, as apparently happened in your case. The real solution would IMO be to add `pyserini` to conda-forge (by submitting a PR to https://github.com/conda-forge/staged-recipes/).

**Comment by lintool** [comment]
Thanks @NeverInAsh !

@MXueguang we should think through our dependency chain a bit more carefully. Maybe for all the neural-related stuff, don't directly include - leaving users the flexibility to install how they wish?

@h-vetinari Yup, conda recipe is a possibility, but not sure if it's over-engineering at this point...

**Comment by NeverInAsh** [comment]
For those who do not want to use neural dependencies can use v 9.3.1 it worked like a charm.

I think a good fix would to include conda channel, it shouldn't be a lot of effort. (IMO)

**Comment by MXueguang** [comment]
yes, seems `faiss` is not supported in Windows.
Without faiss, i.e. working on Sparse search only, earlier version like v 9.3.1 should work.

Regarding the future release, i think we have three options:
1. not install neural-related dependency by default (e.g. transformers, pytorch, faiss), raise installation guide when needed.
2. see how transformers handled faiss dependency, seems they deal with windows/other separately. [here](https://github.com/huggingface/transformers/blob/master/setup.py)
3.  include conda channel. (not familiar with it rn, will take a look, it's good to have this anyway)

**Comment by beauby** [comment]
@MXueguang Faiss is indeed supported on Windows (for CPU indexes for now, GPU indexes coming soon).

**Comment by MXueguang** [comment]
@beauby good to know, thanks!
I'll set up a windows environment and go through the things.

**Comment by h-vetinari** [comment]
> include conda channel. (not familiar with it rn, will take a look, it's good to have this anyway)

Conda has different channels, but they are really a completely separate distribution system from PyPI, which comes with some downsides (extra packaging effort), but large upsides (note: I'm biased), not least consistent packaging that is compatible across the whole conda ecosystem (e.g. no random segfaults/crashes/etc. by co-installing packages, which can happen from PyPI via pip). The point being that you'll probably not have a good time trying to include stuff from conda into your existing packaging, but you can choose to use it as a separate distribution channel.

Within the conda ecosystem, there are many channels, although one should keep the number of used channels to a minimum. `main` (from Anaconda) and `conda-forge` are very closely related and compatible between each other. `pytorch` has some difficult-to-package GPU & ML packages, but unless specifically necessary (like for `bioconda`), I recommend against using more channels.

Note that conda-forge builds `faiss`-packages [as well](https://github.com/conda-forge/faiss-split-feedstock). The "recipe" is open for anyone to improve, and packages are built directly from Github CI. Win, OSX, Linux+GPU is supported, Win+GPU support is around the corner. You can install like `conda create -n my_new_environment -c conda-forge faiss python=3.8`. Note this intentionally leaves out whether it's GPU or CPU (though the distinction is possible via so-called build-strings). This would enable pyserini to depend on either, and if the user's system has a GPU, conda would install faiss with GPU support.

I might be able to help with packagin pyserini for conda-forge, had a brief look today, and currently this is stuck on conda-forge not having enough CI time to successfully build tensorflow (though this problem is in the process of being solved), so 2.3 is not yet available.

**Comment by lintool** [comment]
@MXueguang I think this is independent and shouldn't block v0.12.0 release, right? https://github.com/castorini/pyserini/projects/1

**Comment by MXueguang** [comment]
@lintool yeah, we can release v0.12.0 first and then do conda-forge for v0.12.0

**Comment by MXueguang** [comment]
This can be closed since Faiss is not a mandatory dependency for Pyserini (user installs it based on their environments).
