### ISSUE TITLE
Incorporate S-BERT model for MS MARCO

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#409]
@MXueguang Let's get this into Pyserini? https://github.com/UKPLab/sentence-transformers/blob/master/docs/pretrained-models/msmarco-v3.md

**Comment by MXueguang** [comment]
The passage encode script just need 2 line modification from the ance encode script. so I'll send PR for that. And start indexing since it takes time.

@KaiSun314 Could you go for the question encoding part (also the rest of pipeline) when you get time? 
By taking this as example. https://github.com/castorini/pyserini/blob/737239960e3536e849de1bafe5799af21eff73a3/pyserini/dsearch/_dsearcher.py#L77
and update `dsearch/__main__.py` etc.

**Comment by MXueguang** [comment]
maybe it is better to follow the hugging face usage, https://huggingface.co/sentence-transformers/msmarco-distilbert-base-v3
so that we don't need to add an extra dependency

**Comment by KaiSun314** [comment]
Sounds great, I will do that

**Comment by lintool** [comment]
Do we want this to be part of the next release, or punt?

**Comment by MXueguang** [comment]
this can be closed I think? 
https://github.com/castorini/pyserini/blob/master/docs/experiments-sbert.md

**Comment by lintool** [comment]
I don't think I've done reproduction. Let me do so before we close.

Also, we'll need integration tests - create a separate issue to keep track?

**Comment by MXueguang** [comment]
ah, I didn't notice the doc haven't complete yet...
We need to add hybrid for s-bert too?

Yeah, we need integration tests.

**Comment by lintool** [comment]
Yes, we should add hybrid also.

**Comment by lintool** [comment]
We also need to add a link from the main README: https://github.com/castorini/pyserini/blob/master/docs/experiments-sbert.md

Otherwise it's "invisible".

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/449
