### ISSUE TITLE
Anyway to indicate the cache directory for downloaded indexes?

### ISSUE THREAD

**Issue by ArvinZhuang** [castorini/pyserini#414]
Hi,
Is there any way to instruct the cache directory to download the index? instead of the default .cache in the home folder?

Thanks

**Comment by lintool** [comment]
Not currently... but you can change the directory in the code? PRs to generalize this welcome!

**Comment by MXueguang** [comment]
Yes, It is reasonable to make cache dir configurable. Since some of our pre-built index is to large to simply store under HOME.

transformers can configure cache dir by setting environment dir 'TRANSFORMERS_CACHE'. We can implement something similar, i.e.. 'PYSERINI_CACHE'

@ArvinZhuang for now, you can modify the code here https://github.com/castorini/pyserini/blob/229647961ac973753bd0e23355850d9473f74718/pyserini/util.py#L91

**Comment by ArvinZhuang** [comment]
Hi, I have modified the code and submitted a PR to solve the problem.

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/416
thank you @ArvinZhuang
