### ISSUE TITLE
unit test error

### ISSUE THREAD

**Issue by printfCalvin** [castorini/pyserini#435]
Hello all,

I was trying to replicate some experiments using pyserini. But I got some weird error after I ran `python3 -m unittest`. I'm running it on ubuntu insider windows. Here are the output and the python, java version that I'm using. 
![Screenshot (35)](https://user-images.githubusercontent.com/67453305/111891961-4989ca00-89cd-11eb-97c5-81d498e8f6c2.png)
By the way, since I have so litter experience with this, this could be a straightforward question. If that's the case, I apologize in advance. Thanks for the help.

**Comment by MXueguang** [comment]
Hi @printfCalvin
seems your python3 command was linked to python2.7 accidentally?
Pyserini supports python 3.6+.

**Comment by printfCalvin** [comment]
Thanks for the quick reply. The first command should be `python3 --version` instead of `python --version`. `python3` is indeed linked to Python 3.6.9. sorry about the confusion.

**Comment by MXueguang** [comment]
yeah, but seems the error comes from `/usr/lib/python2.7/runpy.py`.
Maybe link the `python` to `python3.6.9` is needed too.
We assume the default `python` is `python3.6+`, so in our unit tests, their is some tests calling `python` as below:
```
os.system(f'python -m pyserini.fusion --method rrf --runs ' +
                  f'{self.tmp}/anserini.covid-r3.abstract.qq.bm25.txt ' +
                  f'{self.tmp}/anserini.covid-r3.full-text.qq.bm25.txt ' +
                  f'{self.tmp}/anserini.covid-r3.paragraph.qq.bm25.txt ' +
                  f' --output {self.tmp}/anserini.covid-r3.fusion1.txt ' +
                  f'--runtag reciprocal_rank_fusion_k=60 --k 100000')
```
I guess that where the issue is. It calls `python`, which linked to `python2.7` in your environment I think.

Besides if it is convenient for you, I would suggest using anaconda's python environment.

**Comment by printfCalvin** [comment]
Thanks a lot.
