### ISSUE TITLE
Deprecation of tools/scripts/dpr

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#501]
Can we remove these scripts now that these features have been integrated into pyserini?

Okay from pygaggle perspective also right?

cc @KaiSun314

**Comment by KaiSun314** [comment]
I can't seem to get it working in Pygaggle. 

1. It requires a small change to pygaggle/run/evaluate_passage_reader.py (however, due to the current configuration of the pyserini/eval/evaluate_dpr_retrieval.py script, we will need to load in the retrieval file twice, which is expensive - this can be fixed with a change to the evaluate_dpr_retrieval script, but then we'll need to wait until next release).
2. Moreover, I can't seem to import `pyserini.eval` in Pygaggle, which is needed to access the pyserini/eval/evaluate_dpr_retrieval.py script

**Comment by MXueguang** [comment]
removed in https://github.com/castorini/pyserini/pull/621
