### ISSUE TITLE
Problem in running LTR feature extraction pipline

### ISSUE THREAD

**Issue by mfayoub** [castorini/pyserini#604]
I tried to install pyserini using pip, and then I tried to use FeatureExtractor but I got the following error
jnius.JavaException: JVM exception occurred: io/anserini/ltr/feature/SumPooler java.lang.NoClassDefFoundError

I think this is because SumPooler is not inside 'feature' folder and it is now under 'ltr' folder, right?

Then, I uninstalled the pip library, and then I tried to follow Development Installation. I think the installation process worked for me and I copied the jar file from anserini to pyserini. However, when I try any simple code using pyserini. I got the following error.
ModuleNotFoundError: No module named 'pyserini'

So my question is how to use pyserini after doing the development installation. Should my code reside in the same folder as the installed pyserini?

Thanks in advance!

**Comment by lintool** [comment]
@stephaniewhoo can you help with this?

**Comment by stephaniewhoo** [comment]
Hi @mfayoub, sorry for the inconvenience. 

- The SumPooler error is fixed in [here](https://github.com/castorini/pyserini/pull/544). However, this is merged after the latest release(v1.2.0). Once we get to the next release for Pyserini, pip install version will be good.

- Yes, if we use Pyserini by doing the dev installation, the script you need to use Pyserini should be inside of Pyserini/

**Comment by mfayoub** [comment]
Thanks @lintool and @stephaniewhoo for your quick response. That made it work for me.

**Comment by lintool** [comment]
@mfayoub Would you be willing to share what you're using our LTR pipeline for?

**Comment by mfayoub** [comment]
Yes sure. I'm working on building a test collection based on the Avocado Email Collection. So basically, I'm using Pyserini to extract relevance features between query and document pairs.
