### ISSUE TITLE
[QUESTION] Index collection from Python Generator

### ISSUE THREAD

**Issue by cakiki** [castorini/pyserini#894]
Hello, I'm currently working my way through the [DIY indexing tutorial](https://github.com/castorini/pyserini#how-do-i-index-and-search-my-own-documents) and was wondering whether it would be possible to pass a python generator that yields dictionaries instead of a JSON collection to the `-collection`/`-generator` flags.

**Comment by lintool** [comment]
This would be challenging, as Pyserini's indexer is just a shim layer to the underlying Java indexer... you'd need to expose more hooks/abstractions from the Java/Lucene end than what's currently exposed.

However, any such implementation will likely be slow because of (1) Python/Java datatype conversions, and (2) Lucene depends on multi-threading to make indexing fast... and I'm not sure you can get Python's multiprocessing to "connect" with Java in the "right way" to make it fast.

**Comment by cakiki** [comment]
Thank you very much! This does indeed seem not to be worth the effort.

I'll go ahead and close the issue.
